stages:
  - build
  - deploy

cache:
  paths:
    - .yarn
    - node_modules/

build:
  stage: build
  image: node:latest
  artifacts:
    paths:
      - build

  script:
    - yarn install --frozen-lockfile
    - yarn run build:dev
  only:
    - master
