stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn run build:dev
  only:
    - master

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd build
    - dpl --provider=heroku --app=iseplife-front --api-key=$HEROKU_API_KEY
  only:
    - master