image: docker:latest
services:
  - docker:dind

variables:
  FRONT_VERSION: v1.4
cache:
  paths:
    - .yarn
    - node_modules/


stages:
  - test
  - build
  - package

test:
  stage: test
  image: node:14.8.0
  script:
    - npm upgrade --global yarn
    - yarn install --ignore-optional --frozen-lockfile --cache-folder .yarn
    - yarn run build:dev
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'


react-build:
  stage: build
  image: node:14.8.0
  artifacts:
    paths:
      - build/
  script:
    - echo "=== BUILDING REACT PROD ==="
    - yarn install --ignore-optional --frozen-lockfile --cache-folder .yarn
    - yarn run build:dev
  retry: 2
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

docker-build:
  stage: package
  script:
    - echo "=== BUILDING DOCKER IMAGES ==="
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$FRONT_VERSION -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$FRONT_VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

