image: docker:19.03.0
services:
  - docker:19.03-dind

variables:
  FRONT_VERSION: v1.4

cache:
  paths:
    - .yarn
    - node_modules/

stages:
  - test
  - build
  - package

test:
  stage: test
  image: node:12.13.1
  script:
    - npm upgrade --global yarn
    - yarn install --ignore-optional --frozen-lockfile --cache-folder .yarn
    - yarn run build:dev
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'


react-build:
  stage: build
  image: node:12.13.1
  artifacts:
    paths:
      - build/
  script:
    - echo "=== BUILDING REACT PROD ==="
    - yarn install --ignore-optional --frozen-lockfile --cache-folder .yarn
    - yarn run build:dev
  retry: 2
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

docker-build:
  stage: package
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN
  script:
    - echo "=== BUILDING DOCKER IMAGES ==="
    - docker build -t $CI_REGISTRY_IMAGE:$FRONT_VERSION -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$FRONT_VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

