image: docker:latest
services:
  - docker:dind

variables:
  FRONT_VERSION: v1.4

stages:
  - build
  - package
  - deploy

cache:
  paths:
    - .yarn
    - node_modules/

react-build:
  stage: build
  image: node:12.0.0
  artifacts:
    paths:
      - build/
  script:
    - yarn install --frozen-lockfile
    - yarn run build:dev
  only:
    - master
    - feature/ci


docker-build:
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/front:$FRONT_VERSION -t $CI_REGISTRY_IMAGE/front:latest .
    - docker push $CI_REGISTRY_IMAGE/front:$APP_VERSION
    - docker push $CI_REGISTRY_IMAGE/front:latest
  dependencies:
    - react-build
  only:
    - master

